apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: cm9vdHNlY3JldDEyMw==
  MYSQL_DATABASE: ZXhhbV9kYg==
  MYSQL_USER: YXBwX3VzZXI=
  MYSQL_PASSWORD: c2VjcmV0MTIz
